apiVersion: v1
kind: Service
metadata: 
  name: redis
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
  - port: 6379
    targerPort: 6379
  selector: 
    name: redis-pod
    app: demo-voting-app